language: node_js
node_js:
  - 8.11.3
before_script: npm install
script: true
before_install:
  - openssl aes-256-cbc -K $encrypted_e199ff3afb34_key -iv $encrypted_e199ff3afb34_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host www.wangyf.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
  - npm prune --production # 删除devDependencies
  - tar -jcf api-server.tar.bz2 * # 打包并压缩代码
  - scp api-server.tar.bz2 root@www.wangyf.cn:~/ # 复制到阿里云服务器
  - ssh root@wangyf.cn 'mkdir -p api-server && tar -jxf api-server.tar.bz2 -C api-server'